### ISSUE TITLE
Increase performance of lib

### ISSUE THREAD

**Issue by nerg4l** [arubacao/tld-checker#18]
`isTld` uses `in_array` of PHP which has an `O(n)` complexity because it uses linear search. It can be relatively slow with 1500 elements. `RootZoneDatabase::TLDS` could be modified or an other const could be added which stores TLDs in an associative array which would enable the use of `array_key_exists`. `array_key_exists` does linear polling in collisions which is not `O(1)` but quite close to it.

Source of Big-O information: https://stackoverflow.com/questions/2473989/list-of-big-o-for-php-functions

**Comment by Webkadabra** [comment]
@nerg4l good catch! I've fixed this in my fork, hopefully PR will get accepted (https://github.com/Webkadabra/tld-checker)

**Comment by arubacao** [comment]
Thanks I merged it @Webkadabra

**Comment by Webkadabra** [comment]
@arubacao I appreciate it! Thanks for the library and the maintenance!
