### ISSUE TITLE
Third party TLD list

### ISSUE THREAD

**Issue by umpirsky** [arubacao/tld-checker#8]
Hi, I am the author of https://github.com/umpirsky/tld-list, which is basiacally the same thing you did in https://github.com/arubacao/tld-checker/tree/master/build.

I'd like to know if you are interested in using it, and how the format fits.

Cheers!

**Comment by arubacao** [comment]
Hi @umpirsky ,
I did some research before creating this library and nothing was suitable for me.
Your build script does not have any verification or validation. This is too unsafe for me. For now, I'm happy with my own build script.
Cheers

**Comment by arubacao** [comment]
> What kind of validation/verification are you referring to?

E.g. an md5 check of the source `https://data.iana.org/TLD/tlds-alpha-by-domain.txt` like I do [here](https://github.com/arubacao/tld-checker/blob/master/build/build.php#L27). As for the data source, I'd like to stick to the original source :)

**Comment by umpirsky** [comment]
I see, thanks!
